### PR TITLE
[WIP] update and add some unstable APIs

### PR DESCRIPTION
**Pull request by ImUrX**
thought i could update the unstable APIs in websys

### CODE REVIEW

**Comment by ImUrX** [comment]
each time i try to run wasm-bindgen-webidl, it returns
```
Error: compiling WebIDL into wasm-bindgen bindings in file "webidls\enabled\AbortController.webidl", line 2 column 14

Caused by:
    failed to parse webidl at byte position 94
error: process didn't exit successfully: `C:\Users\uri\Documents\wasm-bindgen\target\release\wasm-bindgen-webidl.exe webidls src/features` (exit code: 1)
```

It seems there is an error on comment detection?

**Comment by ImUrX** [comment]
[It](https://github.com/ImUrX/wasm-bindgen/blob/3534499c140c7741d8e871d2e5f29b2b2ec1c837/crates/web-sys/webidls/unstable/Bluetooth.webidl#L7) seems readonly needs to be after [] which I (dont know WebIDL) think are some kind of attributes, is this something that should be fixed on weedle?

**Comment by alexcrichton** [comment]
Sorry I'm not an expert on WebIDL, so maybe? I'm not sure :(

**Comment by ImUrX** [comment]
np, now i need to fix some other issues like #2560 and the error in the cargo test

**Pull request closed without merging**
