### PR TITLE
Add a skip_jsdoc attribute.

### PR DESCRIPTION
**Pull request by jneem**
This adds a `skip_jsdoc` attribute to suppress the generation of jsdoc `@param` and `@returns` comments.

This was motivated by #1847, but I ended up going a different route because I found it awkward to put long descriptions in attributes. The idea is that if you can skip the auto-generated jsdoc, you can comment the parameters and return values yourself:

```rust
/// @param {string} world - The world.
#[wasm_bindgen(skip_jsdoc)]
fn hello(world: &str) {}
```

It's a little sad that this approach doesn't keep the type information in sync, but I still think it's nicer than an alternative like

```rust
#[wasm_bindgen(param(world = "The world."))]
fn hello(world: &str) {}
```
 (especially if the description is longer)

### CODE REVIEW

**Comment by jneem** [comment]
I'm not sure I did the schema-bumping correctly, but I tried to do what's in line with past practice: I bumped the schema version but not the crate versions, which seems to usually happen right when releasing.

**Review by Liamolucko — COMMENTED** [review]
Thanks for this! The code looks good, but could you add a page about this to the guide?

The source Markdown is at `guide/src`, and this should specifically go in `guide/src/reference/attributes/on-rust-exports`.

You also have to add an entry to `guide/src/SUMMARY.md`, otherwise the page won't show up in the table of contents.

Also, yes, you bumped the schema version properly.

**Comment by jneem** [comment]
Thanks for the pointers! I've added a guide entry.

**Review by Liamolucko — APPROVED** [review]
Thanks!

**Comment by qtnx** [comment]
Looks like it's not working on the latest version 0.2.84
```
error: unknown attribute
   --> wasm/src/lib.rs:198:20
    |
198 |     #[wasm_bindgen(skip_jsdoc)]
    |                    ^^^^^^^^^^
```

**Comment by jneem** [comment]
Yes: 0.2.84 was release in February and this was only merged in March.

**Comment by qtnx** [comment]
> Yes: 0.2.84 was release in February and this was only merged in March.

Hmm, so it shouldn't be in the official documentation. Hopefully, a new version will be released soon, it's already April.

**Pull request merged**
