### PR TITLE
Adding in initial support for all HTML*Element interfaces.

### PR DESCRIPTION
**Pull request by jonathanKingston**
I'll keep adding the tests for this today when I get chance. However everything looks to be working locally (so happy to merge whenever you are :+1: ).

### CODE REVIEW

**Comment by jonathanKingston** [comment]
I think this covers all of #447 minus the tests highlighted.

**Comment by jonathanKingston** [comment]
The only issue I can see is the short elements interface names are lowercase:
`HtmlbrElement`

**Comment by jonathanKingston** [comment]
@alexcrichton I changed the camelcasing to use a little helper function which fixing the naming of `HTMLBRElement` to be `HtmlBrElement` in Rust.

**Comment by alexcrichton** [comment]
Nice! The last commit looks good to me as well.

It looks like there's a test failure, but it's likely not your fault as well (cc @xtuc, maybe a webpack bug?). @jonathanKingston want to tweak or comment out the test for now to get CI passing? With https://github.com/rustwasm/wasm-bindgen/pull/559 we can hopefully rewrite these tests to be a bit speedier as well!

**Comment by fitzgen** [comment]
Wow!

**Comment by alexcrichton** [comment]
👍

**Comment by xtuc** [comment]
The error `wasm validation error: at offset 229: byte size mismatch in function section` isn't emitted by Webpack but by Firefox.

**Comment by alexcrichton** [comment]
@xtuc yes but it could be a bug in the wasm file that Webpack produces, right?

**Comment by xtuc** [comment]
Yes that's possible, could you please indicate me how to get the failing binary?

**Comment by alexcrichton** [comment]
Ah it's passed now in that these tests have been enabled on master via other means, but if it comes up again I'll let you know!

**Pull request merged**
