### PR TITLE
Add extends attributes for several types

### PR DESCRIPTION
**Pull request by eminence**
Part of #670 

Marking as WIP because I wasn't able to run tests locally.  If/when travis CI finishes successfully on this PR, feel free to merge

### CODE REVIEW

**Comment by Pauan** [comment]
@eminence Symbol is a value type (like boolean, string, and number), so you have to detect it like this:

```js
typeof x === "symbol"
```

**Comment by fitzgen** [comment]
Will merge when CI comes back green.

**Comment by eminence** [comment]
I think something went wrong during the merge.  I just pushed a fixup

**Comment by eminence** [comment]
We are green!

**Comment by fitzgen** [comment]
Thanks @eminence :)

**Pull request merged**
