### PR TITLE
Add Crypto.randomUUID API

### PR DESCRIPTION
**Pull request by littledivy**
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

Implemented in Node.js, Deno and Chrome/Edge 92

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! If this isn't implemented in Firefox or Safari though I think it needs to be unstable?

**Comment by littledivy** [comment]
Landed in Webkit too https://trac.webkit.org/changeset/281284/webkit
Firefox is working on it https://bugzilla.mozilla.org/show_bug.cgi?id=1723674
The specification is also going to be merged with the WebCrypto spec. https://github.com/WICG/uuid/issues/27

I think it's safe to be in stable?

**Comment by alexcrichton** [comment]
"going to be merged" and "working on it" means that it's not finalized, and web-sys only supports finalized APIs by default.

**Comment by yisibl** [comment]
Firefox 95 has shipped.

**Comment by Dav1dde** [comment]
@alexcrichton is there an update on this or is this still considered unstable?

**Comment by alexcrichton** [comment]
I do not follow web standards to the degree that I know whether this is ready to ship or not.

**Comment by littledivy** [comment]
Sorry for the delay in switching to unstable, I tried earlier but it didn't work...will give it a shot again.

**Review by hamza1311 — APPROVED** [review]
According to [caniuse](https://caniuse.com/?search=randomUUID()), this is implemented by all major browsers and there is no mentioning of it being unstable in either [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) or [W3C docs](https://w3c.github.io/webcrypto/#Crypto-method-randomUUID)

@alexcrichton can you merge this?

**Comment by alexcrichton** [comment]
Ok great!

**Pull request merged**
