### PR TITLE
Add support for empty enum variants and enum variants that start with a digit

### LINKED ISSUE #625: WebIDL: Enable bindings that have unusual enum names
Need to make sure this folder is empty! https://github.com/rustwasm/wasm-bindgen/tree/master/crates/web-sys/webidls/unavailable_enum_ident

### PR DESCRIPTION
**Pull request by afdw**
Fixes #625.

### CODE REVIEW

**Comment by afdw** [comment]
Looks like some tests are failed because of Travis CI problems.

**Comment by fitzgen** [comment]
> Looks like some tests are failed because of Travis CI problems.

Retriggered the job

**Comment by afdw** [comment]
Yes, thanks, it solved the problem.

**Comment by alexcrichton** [comment]
💯

**Pull request merged**
