### PR TITLE
Added File System Access WEBIDL

### PR DESCRIPTION
**Pull request by grenierdev**
Added File System Access draft WEBIDL [[source]](https://wicg.github.io/file-system-access/) to unstable.

Related to #2555

### CODE REVIEW

**Comment by grenierdev** [comment]
I'm not sure how to configure properly the WEBIDL as unstable so it generates `#[cfg(web_sys_unstable_apis)]` on new functions of global interfaces (`Window`, etc).

The `WebGPU.webidl` seems to generate the `#[cfg(web_sys_unstable_apis)]` on `Navigator.gpu` but I can't figure out how.

**Comment by grenierdev** [comment]
Blocked by #2560

**Comment by alexcrichton** [comment]
Looks reasonable to me! Seems fine to land once CI and the corresponding issue are fixed.

**Comment by SpanishPear** [comment]
Is there a reason this didn't land? Tried to use it today and realised it wasn't in `web-sys` :thinking:

**Pull request closed without merging**
