### PR TITLE
Stabilize File System API

### PR DESCRIPTION
**Pull request by daxpedda**
This is stable and available in all browsers by now (except `FileSystemWritableFileStream` on Safari).

WHATWG: https://fs.spec.whatwg.org

- `StorageManager.getDirectory()`: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/getDirectory#browser_compatibility) | [Caniuse](https://caniuse.com/mdn-api_storagemanager_getdirectory)
- `FileSystemSyncAccessHandle`: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle#browser_compatibility) | [Caniuse](https://caniuse.com/mdn-api_filesystemsyncaccesshandle)
- `FileSystemWritableFileStream`: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemWritableFileStream#browser_compatibility) | [Caniuse](https://caniuse.com/mdn-api_filesystemwritablefilestream)
- `FileSystemDirectoryHandle`: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle#browser_compatibility) | [Caniuse](https://caniuse.com/mdn-api_filesystemdirectoryhandle)
- `FileSystemFileHandle`: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle#browser_compatibility) | [Caniuse](https://caniuse.com/mdn-api_filesystemfilehandle)
- `FileSystemHandle`: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle#browser_compatibility) | [Caniuse](https://caniuse.com/mdn-api_filesystemhandle)

### CODE REVIEW

**Review by Liamolucko — APPROVED** [review]

**Comment by Xuanwo** [comment]
Thank you for stabilizing those APIs! Is there a release plan? This will significantly advance https://github.com/apache/incubator-opendal/issues/2442.

**Comment by daxpedda** [comment]
No plans AFAIK.

**Comment by Xuanwo** [comment]
> No plans AFAIK.

How about cutting one to celebrate Christmas :love_letter: ? It's been one month since the last release.

**Comment by daxpedda** [comment]
Feel free to request one in a dedicated issue!

**Pull request merged**
