### PR TITLE
Add note about using custom WebDrivers

### PR DESCRIPTION
**Pull request by thisisrandy**
This updates the docs to reflect the change made in rustwasm/wasm-pack#1127 and discussed in rustwasm/wasm-pack#1126.

### CODE REVIEW

**Comment by thisisrandy** [comment]
@alexcrichton this change actually isn't accurate until rustwasm/wasm-pack#1127 is merged. Could you take a look at that as well please?

**Comment by thisisrandy** [comment]
I see. I saw your fingerprints on something over there and assumed, but I see now that I was mistaken. How would you prefer I handle this? It's a bit awkward to have two contingent PRs to different repos pending.

**Comment by alexcrichton** [comment]
Sorry but I don't help out with wasm-pack any more so I don't know how to coordinate the two repos.

**Comment by thisisrandy** [comment]
Okay then. I think what I'll do is wait for the wasm-pack PR to be resolved (it's been quite some time at this point, but hopefully someone looks at it eventually), and then resubmit this PR to update the docs. Thanks for your help.

**Pull request merged**
