### PR TITLE
test running rustfmt on web-sys bindings.

### PR DESCRIPTION
**Pull request by derekdreery**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh oops, I forgot about this, thanks for looking into it! 

I believe this was done for CI time historically but I think it's fine to merge now. Thanks!

**Comment by alexcrichton** [comment]
I've unfortunately ended up having to undo this in https://github.com/rustwasm/wasm-bindgen/commit/0f0d5ee0fb2ce4f27c5cdc9f18f1862f7643b077 due to [failures to upload](https://dev.azure.com/rustwasm/wasm-bindgen/_build/results?buildId=1887&view=logs&jobId=e07742bd-189a-5079-918b-43f8b2f94b89&j=e07742bd-189a-5079-918b-43f8b2f94b89&t=36f9144f-a45f-5b35-66d0-36ec4e578454) where the formatted file is too large for github.

**Comment by Pauan** [comment]
@alexcrichton I've worked around that in the past by splitting it into multiple separate files. Each file must be less than 50 MB, but you can have *multiple* 50 MB files just fine.

Of course, it's questionable whether we *should* be uploading 50+ MB files in the first place...

**Comment by alexcrichton** [comment]
I think this has to do with generated code so it's unfortunately a bit nontrivial to split up :(

**Pull request merged**
