### PR TITLE
Print error messages to the console in the webgl example

### PR DESCRIPTION
**Pull request by LesleyLai**
Make it a bit easier for debugging shaders.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Out of curiosity, was the thrown exception not showing up in the console? That was the intention at least, and it seems bad if that's not the case!

**Comment by LesleyLai** [comment]
> 
> 
> Thanks! Out of curiosity, was the thrown exception not showing up in the console? That was the intention at least, and it seems bad if that's not the case!

No, at least in my case, nothing shows up in the console if the shaders cannot compile.

**Comment by alexcrichton** [comment]
Hm ok that sounds worrisome! Mind digging in a bit to see why the exceptions aren't showing up in the logs? This is the same pattern we have for a number of our other examples and it'd be a bummer if we needed to change those as well. I wonder if this is a bug in something else by accident or something like that?

**Comment by chinedufn** [comment]
On mobile so can’t easily read the PR diff right now but just in case this is related...:

When WebGL shaders can’t compile they don’t throw an error with the reason. To see what went wrong you need to explicitly print out the shader info log. This is a common pattern is any WebGlProgram.

@LesleyLai I’m noticing a bunch of indentation from some nested functions so would be nice to not have that if possible.

**Pull request closed without merging**
