### PR TITLE
Add @belfz to the team! \o/

### PR DESCRIPTION
**Pull request by fitzgen**
:tada: :balloon: :tada:

### CODE REVIEW

**Comment by jonathan-s** [comment]
🎉

**Comment by alexcrichton** [comment]
🥥

**Comment by belfz** [comment]
Yay, hi guys! 🦀 

Let me introduce myself briefly: I'm primarily a JavaScript/TypeScript developer, currently working at SoftwareMill, which is polish, 100% remote, flat-structure, ~40 people company. I've been playing around with Rust for over a year now & in the meantime I already had a small contribution to the community - I created the [VSC search crates.io plugin](https://marketplace.visualstudio.com/items?itemName=belfz.search-crates-io)!

See you around!

**Comment by fitzgen** [comment]
Awesome! Welcome to the team :)

**Comment by sendilkumarn** [comment]
Welcome @belfz

**Comment by belfz** [comment]
I think there's a little table layout issue on the page - I fixed it in #379 :)

**Pull request merged**
