### PR TITLE
web-sys: Add WebBluetooth to unstable directory

### PR DESCRIPTION
**Pull request by qdot**
WebBluetooth (Chrome, Edge) support. IDL taken from WebBluetooth spec. Includes generated files and updated features.

### CODE REVIEW

**Comment by qdot** [comment]
Tested in Chrome 85 on Windows 10, seems to work ok but have not fully exercised API yet.

**Comment by alexcrichton** [comment]
Thanks for this! Is this a stable web API? If not I think this may need to be in the unstable folder?

**Comment by qdot** [comment]
@alexcrichton Ok, after a small bit of churn due to me trying to figure out how to regenerate the code with the IDL as unstable, I think this is ready to go.

**Comment by alexcrichton** [comment]
Perfect, thanks!

**Pull request merged**
