### PR TITLE
Add __exports. to exported class references when using --no-modules

### PR DESCRIPTION
**Pull request by alippai**
Fixing #204

### CODE REVIEW

**Comment by alippai** [comment]
This introduces a bug if not all classes are exported.

Note: I have no experience writing Rust or using wasm-bindgen, any feedback is appreciated :)

**Comment by alippai** [comment]
The rust2js change is not needed, I'll update this PR soon

**Comment by alexcrichton** [comment]
Thanks for the PR and the report! Recently though https://github.com/rustwasm/wasm-bindgen/pull/191 was targeted at fixing this, although it may not have fixed everything! Do you have an example I could build locally and poke around with to see what's going on?

**Comment by alippai** [comment]
Oh, that was my colleague, I'm working on the same piece of code.
```
enum DigestImpl {
    Sha1(sha1::Sha1),

...

#[wasm_bindgen]
pub struct Digest(Option<DigestImpl>);

#[wasm_bindgen]
impl Digest {

...

#[wasm_bindgen]
pub fn sha1() -> Digest {
    Digest(Some(DigestImpl::Sha1(Default::default())))
}
```

**Comment by alippai** [comment]
Generating code like this could work also:
```
class X {}
__exports.X = X;
function c() {
  return X.__construct();
}
```

**Comment by alippai** [comment]
It was my bad wasm-bindgen-cli version :(

**Comment by alippai** [comment]
Also I have to check how cargo works, I didn't expect it to be outdated (it was version 0.2.8 instead of 0.2.10).

**Comment by alexcrichton** [comment]
Ah ok, glad to hear that it's working now!

**Comment by alippai** [comment]
@alexcrichton does it make sense for the wasm-bindgen-cli to check the Cargo.lock file (if available) for the correct wasm-bindgen version? It could help with the newbie mistakes like mine.

**Comment by alippai** [comment]
It is, thanks!

**Comment by alexcrichton** [comment]
Hm yeah that could work! We could do something like try to learn what the `wasm-bindgen` version is in the background, and if successful print a warning if that looks to be newer than the local version

**Pull request closed without merging**
