### PR TITLE
Add experimental `ViewTransition` interface

### PR DESCRIPTION
**Pull request by tigerros**
This adds the experimental `ViewTransition` interface. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/ViewTransition) and [W3C specs](https://drafts.csswg.org/css-view-transitions/#the-domtransition-interface). I hope experimental APIs are allowed.

I followed the contributing guidelines, but let me know if I did something wrong.

### CODE REVIEW

**Review by daxpedda — CHANGES_REQUESTED** [review]
LGTM!
Could you add an entry to the changelog?

**Comment by tigerros** [comment]
Added.

**Review by daxpedda — APPROVED** [review]
Thanks!
Just waiting for CI.

**Comment by tigerros** [comment]
@daxpedda I wanted to ask an additional question, when can it be moved into the `webidls/enabled` directory? I looked at the contributing guide and there was no mention of this.

**Comment by daxpedda** [comment]
We don't have an official guidelines for this. Basically when we *think* that the API isn't going to change anymore.

It's a candidate recommendation, so I'm assuming this isn't going to change anymore, but it's only implemented by Chromium and has [very low usage across the web](https://chromestatus.com/metrics/feature/timeline/popularity/4383).

Considering how close this is to recommendation I would prefer to wait unless there is a strong incentive otherwise.

**Comment by tigerros** [comment]
Alright. If you're wondering, the reason why I added this is because someone requested this as a feature in [Dioxus](https://github.com/DioxusLabs/dioxus), which is an SPA and thus would benefit quite a bit from this.

**Pull request merged**
