### PR TITLE
lib: take_last_exception; remove return

### PR DESCRIPTION
**Pull request by Horki**
@alexcrichton removed return from `take_last_exception`; please test

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Could you describe in a bit more detail though what the purpose of this is?

**Comment by Horki** [comment]
@alexcrichton to implement the `implicit return`, AFAIK rust convection is to use return statement *only* for "early returns"
(from "Programming Rust" book - Jim Blandy & Jason Orendorff)
- fell free to close branch, due to insignificant change

**Comment by alexcrichton** [comment]
Ah ok, thanks for the info! I personally prefer the style in the source for returning a bare variable name, so I'm going to close in that case.

**Comment by Horki** [comment]
Thanks for the quick feedback, oddly this is the only place where explicit return is consumed; tough it would look cleaner and more idiomatic.

**Pull request closed without merging**
