### PR TITLE
Add RTCPeerConnection connectionState

### PR DESCRIPTION
**Pull request by erik-moqvist**

### CODE REVIEW

**Comment by erik-moqvist** [comment]
Anyone that can review this? Thanks.

**Comment by eerimoq** [comment]
Anything else I have to do to get this merged? I'm lost.

**Review by daxpedda — APPROVED** [review]
Even though Firefox doesn't support this, I confirmed that this is already stable according to the W3C: https://www.w3.org/TR/webrtc/#rtcpeerconnectionstate-enum.
Not sure what `wasm-bindgen`s usual convention for something like this is.

LGTM.
(I'm not a maintainer)

**Comment by eerimoq** [comment]
Would be lovely to have it merged. =)

**Comment by eerimoq** [comment]
I'm still interested in getting this merged.

**Comment by alexcrichton** [comment]
Thanks and sorry for the delay!

**Comment by johanhelsing** [comment]
@erik-moqvist what was the difference in this pr compared to #3337 ? I'm just curious. Also don't feel like you have to answer have a lot on your plate. Nice to have this in place ❤️

**Comment by daxpedda** [comment]
#3337 actually included many more APIs that this one doesn't.

**Pull request merged**
