### PR TITLE
Add scrollHeight, and scrollTop to allow scrolling

### PR DESCRIPTION
**Pull request by vthg2themax**
Let me know if there's anything else you need.

### CODE REVIEW

**Comment by vthg2themax** [comment]
Is your windows test machine not working to cause failing tests, or did I forget something?

**Comment by alexcrichton** [comment]
Thanks for the PR! This source, however, is auto-generated from the WebIDL files in this repository. CI checks that the generated source matches what we'd expect, so to alter the source you need to modify the code generator or the WebIDL files, not just the source directly.

**Comment by vthg2themax** [comment]
Thank you very much! I will amend my changes to the correct spot, and try again.

**Comment by vthg2themax** [comment]
I changed the webIDL, it looked correct, does that mean I should not have also changed the output?

**Comment by alexcrichton** [comment]
Landed in https://github.com/rustwasm/wasm-bindgen/pull/2458

**Pull request closed without merging**
