### PR TITLE
cli-support: Remove Node.js specific passStringToWasm

### PR DESCRIPTION
**Pull request by josephlr**
Reverts #1391 (CC #1313)

Now that Node has encodeInto it can use the same path as the normal Web
Browser code (that avoids calling into the C++ code, see #1470 ). Node 12,13, and 14
have this method, so it is now fairly well supported.

@alexcrichton @RReverser, what benchmarks should I run to see if this is actually a speedup for ASCII strings? It looks like the existing benchmarker framework is intended for the Web Broswer.

Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Comment by alexcrichton** [comment]
Sounds reasonable to me, thanks!

**Comment by RReverser** [comment]
> what benchmarks should I run to see if this is actually a speedup for ASCII strings?

I don't think it should, because we already used `Buffer.write` in Node.js. While it was Node-specific, it provided same functionality as the experimental `encodeInto` in browsers - writing to an existing memory view.

**Comment by josephlr** [comment]
> > what benchmarks should I run to see if this is actually a speedup for ASCII strings?
> 
> I don't think it should, because we already used `Buffer.write` in Node.js. While it was Node-specific, it provided same functionality as the experimental `encodeInto` in browsers - writing to an existing memory view.

Oh I mainly meant the initial ASCII loop (that's just pure JS) that occurs before `encodeInto` that was added in #1470, but not for Node.

**Comment by RReverser** [comment]
Ah right, that might have some impact.

**Pull request merged**
