### PR TITLE
add WebUSB WebIDL

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**
issue #1694

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! We in general only add stage 3 and beyond proposals to this repository. I can't seem to find documentation, but do you know at what stage in the standards process this proposal is at?

**Comment by MarcAntoine-Arnaud** [comment]
I don't know where we can find the stage of the proposal...
But this patch don't work, I cannot access to USB feature (in the documentation generated with: `cargo doc --all-features`. Do you have any idea why ?

**Comment by Pauan** [comment]
@alexcrichton I don't know what stage it is, but it is marked as [Experimental](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Conventions_definitions#Experimental) on MDN, and only Chrome and Opera have support for it right now.

**Comment by Pauan** [comment]
I wonder if maybe we should have support for unstable APIs, perhaps behind an `unstable-api` feature or something like that.

And we would reserve the right to break anything behind `unstable-api` at any time, for any reason, even in minor releases.

**Comment by alexcrichton** [comment]
Ok so it sounds like we shouldn't add this as-is because it's not an official spec yet, but I like the idea of having experimental specs here that we can break at any time. Prior art for that I'm aware of isn't to use Cargo features but rather `RUSTFLAGS=--cfg=web_sys_unstable_apis` or something like that.

That way it's a bit more experimental in that it forces consumers to always compile with the right flags. How's that sound to enable this?

**Comment by Pauan** [comment]
> How's that sound to enable this?

That sounds reasonable to me. It means that libraries will have a harder time relying upon unstable features, so they will be mostly used by applications, which is how it should be.

**Comment by MarcAntoine-Arnaud** [comment]
@Pauan @alexcrichton thanks for comments.
I'm agreed it make sense to put it in unstable api.

**Comment by alexcrichton** [comment]
This hasn't seen movement in quite some time now so I'm going to close this, feel free to resubmit it though!

**Comment by alexcrichton** [comment]
FWIW I've opened https://github.com/rustwasm/wasm-bindgen/issues/1950 to track longer-term about how we plan to support unstable WebIDL files.

**Pull request closed without merging**
