### PR TITLE
Clipboard API

### PR DESCRIPTION
**Pull request by vojta7**
Adds Clipboard API (https://www.w3.org/TR/2019/WD-clipboard-apis-20190605/)

Linked issues:
#2097

### CODE REVIEW

**Comment by vojta7** [comment]
Some tests are failing because there is already a specified subset of Clipboard API in [ClipboardEvent.webidl](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/webidls/enabled/ClipboardEvent.webidl). To my understanding, it is part of the same working draft, so it should be unstable.

How should I resolve this conflict? Remove old specification and keep only content of my pull request (if so in unstable or enabled?), or just ignore it?

**Comment by alexcrichton** [comment]
If it was an already-unstable API I think it's fine to delete the original WebIDL in favor of the new unstable WebIDL

**Comment by vojta7** [comment]
I don't understand why is the remaining test failing. It seems just like the wrong order of declarations, can I fix it somehow?

**Comment by alexcrichton** [comment]
This could perhaps be instability in the bindings generator (maybe a hash map somewhere?) or perhaps a merge that needs to happen before regenerating?

**Comment by Pauan** [comment]
@vojta7 You probably just have a different version of Rust, make sure your Rust is up to date (`rustup update`) and that you're on the Stable channel. You should also try running `cargo update` in the wasm-bindgen repository.

**Comment by vojta7** [comment]
@Pauan I tried your suggestions, but the generated code is still the same.

**Comment by vojta7** [comment]
I did also try to rebase onto the current master (last force push), but the tests are still failing.

**Comment by Pauan** [comment]
@vojta7 Okay, then it's probably caused by non-determinism in the bindings generator, let me take a look.

**Comment by Pauan** [comment]
@vojta7 Since https://github.com/rustwasm/wasm-bindgen/pull/2101 was merged, could you rebase and try again?

**Comment by vojta7** [comment]
Thank you for your time :), it did help.

I also think that #1978 may have failed due to the same nondeterminism.

**Comment by Pauan** [comment]
Thanks!

**Pull request merged**
