### PR TITLE
Allow using include_str! in typescript_custom_section consts

### PR DESCRIPTION
**Pull request by coolreader18**
As it says in the title. This would be useful for separating type definitions from the code, and you would be able to get syntax highlighting for the typescript in your editor as well.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! I fear this is a bit heavyweight though reimplementing the macro here, is there a way we can get rustc to expand the macro for us?

**Comment by coolreader18** [comment]
Possibly? I think it would require typescript custom sections to be specially compiled with the program and actually referenced from whatever code the CLI then calls. Idk, I'm not too familiar with the architecture of this project but I don't think there are any APIs in `proc_macro` that we can call to evaluate the macro.

**Comment by alexcrichton** [comment]
I think this just needs to go through to a custom section though, right? Could the code for the custom section allow further compiler expansion in it?

**Comment by coolreader18** [comment]
Maybe something like a struct with a generic type `T` that holds a `syn::Expr` that can be encoded into `T` by using the Expr somehow? I'm not quite sure how the backend works between the macro and CLI.

**Comment by coolreader18** [comment]
Basically, the attribute macro only has access to the AST of the item, no macros are expanded at all.

**Comment by coolreader18** [comment]
Oh wow, I did not know that you could resolve merge conflicts from the GitHub website.

**Comment by alexcrichton** [comment]
Er sorry so what I mean is that this isn't going to merge as-is. We don't want to get in the business of reimplementing macros. Macros can expand to other macro invocations, so if possible we may just need to tweak the expansion to allow that. Otherwise this may just be out of luck for now.

**Comment by coolreader18** [comment]
I understand that. I think what I might try to implement is a custom type that holds a `syn` node, and in where it implements ToTokens it just injects its node.

**Comment by coolreader18** [comment]
If that doesn't work out, I'm fine with closing this PR.

**Comment by alexcrichton** [comment]
That sounds reasonable to me I think! Feel free to post here with results!

**Comment by alexcrichton** [comment]
Ok I'm gonna close this for now to clear out our PR list a bit, but feel free to resubmit with results!

**Pull request closed without merging**
