### PR TITLE
Enable OptionIntoWasmAbi and OptionFromWasmAbi for ast::ImportEnum, RTCRtpTransceiver.webidl

### PR DESCRIPTION
**Pull request by alexlapa**
Some notes:
1. Actually `OptionIntoWasmAbi` for `ast::ImportEnum` can be safely deleted since its not being used in `bindings.rs`.
2. I believe that other disabled webidl's can be enabled.
3. Test should succeed on current Safari Technology Preview (12.2) but i don't know how to run `cargo test` on preview version. Latest Chrome and FF are ok.

Looking forward to your feedback (any :smile: )

### CODE REVIEW

**Comment by alexcrichton** [comment]
This looks great to me, thanks!

Mind adding some tests as well in `tests/wasm/*` specifically for `Option<ImportedEnum>` as well?

**Comment by alexlapa** [comment]
@alexcrichton ,

Sure! But i will be away for few days, so i guess i will do it by the end of next week.

**Comment by alexcrichton** [comment]
Ok no worries!

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
