### PR TITLE
js-sys: Atomics support for BigInt64Array

### LINKED ISSUE #3121: How to operate BigInt64Array with Atomics
### Summary

I want to operate BigInt64Array with Atomics, but i found that the function Atomics.add only allows i32

When passing in the i32 type, it generates error like this:
image

### Additional Details

some codes:

Rust:
```rust
#[wasm_bindgen]
pub fn test(origin_shared_buf: js_sys::SharedArrayBuffer) {
    let typedarray = js_sys::BigInt64Array::new(&origin_shared_buf);
    js_sys::Atomics::Add(&typedarray, 0, 1000).unwrap();
}
```

Javascript:
```js
const originSharedBuf = new SharedArrayBuffer(8);

test(originSharedBuf)
```

### PR DESCRIPTION
**Pull request by daidr**
Fixes #3121 

This pr adds the following methods for manipulating BigInt64Array:
`Atomics::add_bigint`, `Atomics::and_bigint`, `Atomics::compare_exchange_bigint`, `Atomics::exchange_bigint`, `Atomics::load_bigint`, `Atomics::or_bigint`, `Atomics::store_bigint`, `Atomics::sub_bigint`, `Atomics::wait_bigint`, `Atomics::wait_with_timeout_bigint`, `Atomics::xor_bigint`

### CODE REVIEW

**Review by Liamolucko — COMMENTED** [review]
You should add some docs to the new methods - probably just something along the lines of 'a version of `Atomics.<name>` which takes an `i64` instead of a `i32`, for use with `BigInt64Array` / `BigUint64Array`'.

**Review by Liamolucko — APPROVED** [review]
Thanks!

**Comment by viliml** [comment]
You forgot `notify`.

**Comment by guybedford** [comment]
@viliml FYI this is now being included in https://github.com/wasm-bindgen/wasm-bindgen/pull/4876.

**Pull request merged**
