### PR TITLE
Bump versions for 0.2.90 release

### LINKED ISSUE #3755: Request for new release of `web-sys` as `0.3.67` to include stable `FileSystem` API support
### Motivation

The pull request https://github.com/rustwasm/wasm-bindgen/pull/3745 has stabilized the `File System` APIs, eliminating the need for `web_sys_unstable_apis`. This update paves the way for downstream projects to develop features such as those discussed in https://github.com/apache/incubator-opendal/issues/2442.

### Proposed Solution

Bump a new version of `web-sys` to current changes in the main branch.

### Alternatives

None

### Additional Context

The last release of `web-sys` is `0.3.66` at `2023-11-28`.

### PR DESCRIPTION
**Pull request by gabrielgrant**
fixes #3755

### CODE REVIEW

**Comment by gabrielgrant** [comment]
Looks like @thomasetter & @Liamolucko landed a CI fix a few days ago (thank you!). Not sure if #3680 also needs to be landed before a release? Or if there's anything else in particular blocking this?

**Review by daxpedda — CHANGES_REQUESTED** [review]
Would you mind fixing the changelog?
I think we can go ahead with this afterwards.

**Comment by gabrielgrant** [comment]
Ah, good catch, Donezo! (hope that's what you meant? didn't see anything about this in the publishing instructions, so submitted a PR to update them too: #3765 )

**Review by daxpedda — APPROVED** [review]

**Comment by gabrielgrant** [comment]
are there more reviews needed here, or what are the next steps in getting this out this door?

**Comment by daxpedda** [comment]
No next steps for now, will be done soon!

**Comment by daxpedda** [comment]
Done.
Thank you @gabrielgrant.

**Comment by gabrielgrant** [comment]
awesome, thank you @daxpedda !

**Pull request merged**
