### PR TITLE
Bump `walrus` to v0.20

### LINKED ISSUE #2389: Support DWARF in wasm-bindgen
### Motivation

Chrome, Firefox and now also Sentry support DWARF for WebAssembly as debug format. In particularly for crash reporting systems like Sentry DWARF is a very important tool to create accurate stack traces for production builds of web assembly applications.

This issue was previously brought up in #1981.

### Proposed Solution

Most likely the bulk of the implementation will be in walrus (see https://github.com/rustwasm/walrus/issues/67).

### PR DESCRIPTION
**Pull request by daxpedda**
Just checking what CI says for now.

Fixes #2389.

### CODE REVIEW

**Comment by daxpedda** [comment]
Thank you @Liamolucko for solving the discovered issue in https://github.com/rustwasm/walrus/pull/245.

**Comment by daxpedda** [comment]
So I did try the new DWARF debugging support, but it fails pretty fast for me:
```rust
fn main() {
    panic!("test");
}
```
`cargo build --target wasm32-unknown-unknown`
`wasm-bindgen target/wasm32-unknown-unknown/debug/test.wasm --target web --keep-debug`
```
thread 'main' panicked at 'assertion failed: self.row.address_offset >= self.prev_row.address_offset', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.26.2/src/write/line.rs:469:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: gimli::write::line::LineProgram::op_advance
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.26.2/src/write/line.rs:469:9
   4: gimli::write::line::LineProgram::end_sequence
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.26.2/src/write/line.rs:338:26
   5: walrus::module::debug::dwarf::ConvertContext<R>::convert_line_program
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/walrus-0.20.1/src/module/debug/dwarf.rs:210:33
   6: walrus::module::debug::dwarf::ConvertContext<R>::convert_attributes
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/walrus-0.20.1/src/module/debug/dwarf.rs:47:36
   7: <walrus::module::debug::ModuleDebugData as walrus::emit::Emit>::emit
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/walrus-0.20.1/src/module/debug/mod.rs:217:17
   8: walrus::module::Module::emit_wasm
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/walrus-0.20.1/src/module/mod.rs:368:13
   9: wasm_bindgen_cli_support::Output::_emit
             at /home/user/rust/wasm-bindgen/crates/cli-support/src/lib.rs:664:26
  10: wasm_bindgen_cli_support::Output::emit
             at /home/user/rust/wasm-bindgen/crates/cli-support/src/lib.rs:657:9
  11: wasm_bindgen_cli_support::Bindgen::generate
             at /home/user/rust/wasm-bindgen/crates/cli-support/src/lib.rs:306:9
  12: wasm_bindgen::rmain
             at /home/user/rust/wasm-bindgen/crates/cli/src/bin/wasm-bindgen.rs:155:5
  13: wasm_bindgen::main
             at /home/user/rust/wasm-bindgen/crates/cli/src/bin/wasm-bindgen.rs:87:21
  14: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
```

**Comment by daxpedda** [comment]
Took me some time to figure out how exactly Wasm DWARF debugging in the browser works in general, but got it to work.
The bug described before can just be skipped by running in release mode, because it's just a `debug_assert!`.

**Comment by daxpedda** [comment]
I did some more research on this today and I think this generally works out.
Chrome doesn't requiring source maps but Firefox does, which was part of the initial confusion I had at first.

I'm concerned about the `debug_assert!` we are hitting above, but I don't know much about the details here.
@guybedford would you mind taking a look at that?
Let me know if I can do anything to help.

**Comment by daxpedda** [comment]
Currently stuck on https://github.com/rustwasm/walrus/issues/247.

**Comment by d3lm** [comment]
Any updates on this?

**Comment by guybedford** [comment]
Walrus 0.20.2 has just been released thanks to @nokotan which looks like it should now resolve this issue.

**Comment by daxpedda** [comment]
Thanks @guybedford for the ping!
Thanks @nokotan for fixing this!

**Comment by d3lm** [comment]
Thank you all! This is awesome 🔥

**Comment by d3lm** [comment]
Is there a chance to get a new version published with this?

**Comment by daxpedda** [comment]
Currently waiting for an outcome on https://github.com/rustwasm/wasm-bindgen/pull/3709, then I'm happy to push for a new release.

**Pull request merged**
