### PR TITLE
Add unit test for HtmlHrElement web_sys binding

### PR DESCRIPTION
**Pull request by twilco**
Hello again!  Fairly certain this test will pass, but unfortunately I can't seem to get cargo to find any tests at all.

```
~/projects/wasm-bindgen/crates/web-sys 
$ cargo test --target wasm32-unknown-unknown 
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s                                                                                                                                                                                                              
     Running /Users/twilcock/projects/wasm-bindgen/target/wasm32-unknown-unknown/debug/deps/all-a5c63a8c7fc00a5f.wasm
    Finished release [optimized] target(s) in 0.18s                                                                                                                                                                                                                        
     Running `/Users/twilcock/projects/wasm-bindgen/target/release/wasm-bindgen-test-runner /Users/twilcock/projects/wasm-bindgen/target/wasm32-unknown-unknown/debug/deps/all-a5c63a8c7fc00a5f.wasm`
no tests to run!
     Running /Users/twilcock/projects/wasm-bindgen/target/wasm32-unknown-unknown/debug/deps/wasm-d82521c4d7864ee1.wasm
    Finished release [optimized] target(s) in 0.16s                                                                                                                                                                                                                        
     Running `/Users/twilcock/projects/wasm-bindgen/target/release/wasm-bindgen-test-runner /Users/twilcock/projects/wasm-bindgen/target/wasm32-unknown-unknown/debug/deps/wasm-d82521c4d7864ee1.wasm`
Running server on http://127.0.0.1:8000  
```         

Is there some flag or part of the command that I am missing?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

We're prototyping a new test framework in this crate currently, so the test there is running a server in the background for you to visit in a web browser and confirm the tests pass. It could certainly be more informative though! (we also don't have a lot of docs in this repo)

If you're curious to run headless tests you can also run with `CI=1` in the environment

**Comment by twilco** [comment]
Yeah, the new framework is much better to work with, so props to you all on that!

When I go to the server it lists in the message, all I see is a message that says "Loading scripts...".  In the console, there is the following error:

```
wasm-4faccd638d53fbc2:180 Uncaught Error: descriptor for id='contextMenu' not found
    at GetOwnOrInheritedPropertyDescriptor (wasm-4faccd638d53fbc2:180)
    at wasm-4faccd638d53fbc2:1610
```

Should the results of the tests be displaying on the webpage?

**Comment by twilco** [comment]
Just kidding...I was using Chrome, not Firefox 😅 all good!

**Comment by alexcrichton** [comment]
@twilco oh dear that sounds bad! Mind opening an issue? The tests should definitely run in all the browsers!

**Comment by twilco** [comment]
Done!  #595

**Pull request merged**
