### PR TITLE
Added web-sys dom example withot npm and webpack

### PR DESCRIPTION
**Pull request by ibaryshnikov**
Solves #1034. The same example as in **dom** folder, but using vanillajs.

### CODE REVIEW

**Comment by afdw** [comment]
Does not it show the same as [the `no_modules` example](https://github.com/rustwasm/wasm-bindgen/tree/091eaa66f36c3b1cf8c4c2c556e2067383c16670/examples/no_modules)?

**Comment by ibaryshnikov** [comment]
@afdw mostly yes
May be it's better to put more examples in a separate repo, i don't know

**Comment by alexcrichton** [comment]
Sorry for the delay, and thanks for the PR! I wonder if this could be included in the existing `no_modules` example perhaps? I think the Rust code here is the exact same, right, it's just the surrounding setup?

**Comment by ibaryshnikov** [comment]
@alexcrichton yes, the Rust part is the same, and the JS part is slightly different. A made a separate commit, so you can check the [diff](https://github.com/ibaryshnikov/wasm-bindgen/commit/ead95baa4d67205d7be57ed060f33bfe758f778c)

**Comment by alexcrichton** [comment]
Ok cool! Perhaps this could be folded in with the existing `no_modules` example then? (as that's just showing off how DOM things still work in `--no-modules` mode)

**Comment by ibaryshnikov** [comment]
@alexcrichton great idea, updated the pr

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
