### PR TITLE
Update webtransport IDL to the april 5th version

### PR DESCRIPTION
**Pull request by mriise**
Some updates to the IDL.

related: #3344

### CODE REVIEW

**Comment by jneem** [comment]
It looks like the CI failure is caused by an update to `bumpalo` that requires a new rustc version. Updating the CI to run ui-tests on `1.60` should fix it.

**Comment by daxpedda** [comment]
Raising the CI to 1.60 should probably be done in a separate PR.

**Comment by mriise** [comment]
> Raising the CI to 1.60 should probably be done in a separate PR.

#3409 :+1:

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
