### PR TITLE
Getting the `no-modules` TypeScript `*.d.ts` Files Working

### PR DESCRIPTION
**Pull request by aaron-human**
Partially based on https://github.com/rustwasm/wasm-bindgen/issues/693.

The current `--target no-modules` TypeScript declaration files don't correctly describe what the JS interface looks like:
* The functions exported via `extern {` and `#[wasm_bindgen]` are stored in the `wasm_bindgen` namespace, but the TypeScript declaration files don't put them in any namespace.
* Everything else at the root level of the TypeScript file was `export`d. As of TypeScript 3.8.3, that meant it wasn't visible. So those were switched over to `declare` statements.

This tries to fix the above by adjusting the output for just `no-modules`. It also removes the bunch of extra spaces at the end of the declaration file.

As an example, the output went from:
```typescript
/* tslint:disable */
/* eslint-disable */
/**
* @param {number} id
*/
export function call_in(id: number): void;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly call_in: (a: number) => void;
}

/**
* If `module_or_path` is {RequestInfo} or {URL}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {InitInput | Promise<InitInput>} module_or_path
*
* @returns {Promise<InitOutput>}
*/
export default function init (module_or_path?: InitInput | Promise<InitInput>): Promise<InitOutput>;
        
```
To:
```typescript
declare namespace wasm_bindgen {
	/* tslint:disable */
	/* eslint-disable */
	/**
	* @param {number} id
	*/
	export function call_in(id: number): void;
	
}

declare type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

declare interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly call_in: (a: number) => void;
}

/**
* If `module_or_path` is {RequestInfo} or {URL}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {InitInput | Promise<InitInput>} module_or_path
*
* @returns {Promise<InitOutput>}
*/
declare function wasm_bindgen (module_or_path?: InitInput | Promise<InitInput>): Promise<InitOutput>;

```
## Testing

When I ran `cargo test` and `cargo test --target wasm32-unknown-unknown` on my local setup, it reported all passes.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! Would it be possible to add tests for this specifically too? I believe `crates/typescript-tests` doesn't currently use `--no-modules`, but perhaps a separate entry point and/or a separate test for `--no-modules` could be added?

Other than that the changes look great here!

**Comment by aaron-human** [comment]
Ok, I'll see if I can setup some tests.

**Comment by aaron-human** [comment]
Ok, the tests should now try to build with `no-modules` and then verify that TypeScript doesn't reject the built `typescript_tests.d.ts`. That's at least the file I usually use. Not sure if the `*.bg.d.ts` files also need to be tested. Or if the files need to be built against something (i.e. to produce an actual JS output file). What's in now was enough to catch when I manually dumped a junk string into `typescript_tests.d.ts`, so it's at least validating the syntax.

**Comment by aheadmode** [comment]
@alexcrichton

**Comment by alexcrichton** [comment]
Thanks! For the test though it looks like this just asserts that it parses correctly, but could some JS be written which consumes the wasm-bindgen generated JS? That way we can ensure the expected idioms all typecheck and information is all listed as we'd expect.

**Comment by aaron-human** [comment]
@alexcrichton The tests now build the (no-modules) `*.d.ts` files against `*.ts` files very similar to those in `src`. The exact `*.ts` files were modified to try and remove the `import` statements and otherwise switch things away from using JS modules. I was aiming to avoid copying/committing the modified `*.ts` files in `src`; didn't want to make future maintainers have to manually keep the two variants in sync.

**Comment by aaron-human** [comment]
Any chance this will get merged? It should be ready to review.

**Comment by alexcrichton** [comment]
Er apologies I missed that this was ready!

I'm not sure what the test is doing though, what's with all the `sed`? I would hope that we wouldn't have to doctor the output, otherwise that seems like a bug that needs fixing in wasm-bindgen.

**Comment by aaron-human** [comment]
The testing changes try to re-use the existing typescript testing that have been setup for the "--target web" case. The `sed` and `grep` calls in the script are to copy TypeScript files from "src" into a new (temporary) "src_no_modules" directory while also renaming things inside the files so they'll work with `--target no-modules` rather than `--target web`. I've added more comments so it's clearer that this is going on. Though the overview is that:

* The files have dropped any lines with "import". Since "no-modules" has no modules, imports aren't needed.
* The "wbg" namespace (which is where the tests imported the API to) has been replaced with "wasm_bindgen" (the namespace that "no-modules" exports into).
* I skipped all the TypeScript test files that mentioned importing the "../pkg/typescript_tests_bg.wasm" (by excluding files with "_bg.wasm") as I don't know what that file does.

I was aiming to re-use the existing tests rather than writing up new ones, as I'm not too well versed in all of the binding generation functionality. (The project that got me to set this up really only used "call Rust from JS" and "call JS from Rust" with fairly simple argument/return types.) I also figured it'd be nice to not have separate files for testing "--target web" vs "--target no-modules".

**Comment by alexcrichton** [comment]
Ah I see, thanks for clarifying! Sounds good to me!

**Pull request merged**
