### PR TITLE
20240424 webauthn idls

### PR DESCRIPTION
**Pull request by Firstyear**
Update Webauthn IDLs to Level 3

### CODE REVIEW

**Comment by daxpedda** [comment]
Checking the [spec](https://www.w3.org/TR/webauthn-3/) I can see that its still in the draft stage. We usually make those APIs unstable.

We made exceptions in the past for APIs that are unlikely to change e.g. because they are so [widely used](https://chromestatus.com/metrics/feature/popularity) that they can't change without breaking the web, which I assume is not the case here.

**Comment by Firstyear** [comment]
They are pretty unlikely to change though, since a lot of is it based on webauthn-l2. Regardless, we can just wait I guess?

**Comment by daxpedda** [comment]
> They are pretty unlikely to change though, since a lot of is it based on webauthn-l2.

Just looking at the repo it seems to me that there are still a lot of small details up for change.

> Regardless, we can just wait I guess? 

Moving it behind unstable is what we usually do.

**Comment by Firstyear** [comment]
What's the right way to mark this "unstable" then?

**Comment by daxpedda** [comment]
Just move the WebIDL files from the `enabled` folder into the `unstable` one and run the generator again.

Let me know if you run into any problems.

**Comment by daxpedda** [comment]
Replaced by #4000.

**Pull request closed without merging**
