### PR TITLE
Update scrollHeight and scrollTop

### PR DESCRIPTION
**Pull request by vthg2themax**

### CODE REVIEW

**Comment by vthg2themax** [comment]
I did this all in one go. Can you tell me what might be wrong?

**Comment by alexcrichton** [comment]
No worries! I think this is a formatting "error" due to a more recent version of rustfmt, but otherwise looks great. Thanks!

**Comment by vthg2themax** [comment]
Thank you very much for approving this! Did the other version of this pull request have the same problem then? I just want to make sure that I have good code outputs.

**Comment by alexcrichton** [comment]
Probably? I didn't check.

**Pull request merged**
