### PR TITLE
feat(extends): extend promise

### PR DESCRIPTION
**Pull request by robertohuertasm**
Related to #670 

Extends `Promise`.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@fitzgen I've just seen your message. I pushed a new commit amend to force  `appveyor` to restart and see if we're lucky this time.

**Comment by robertohuertasm** [comment]
I guess we're not :stuck_out_tongue_winking_eye:

**Comment by alexcrichton** [comment]
Ah yeah this is fine, thanks!

We'll see what happens with AppVeyor later probably...

**Comment by eminence** [comment]
> [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)


FWIW, I've seen that Cargo error on my own personal windows machine several times.  It always clears up by itself a minute later

**Pull request merged**
