### PR TITLE
Update `RtcPeerConnection` with `connection_state`

### PR DESCRIPTION
**Pull request by johanhelsing**
I wanted access to the `onconnectionstatechange` event, so I tried to follow the readme in the `web-sys` folder and update the idl for `RtcPeerConnection` and related definitions as needed.

However, everything is building now, but when trying it out in practice, I don't actually see the event firing... I'm, not really sure why though, (if the browser is just not sending the event or it's some other reason).

Still, perhaps this might be of use if someone needs more up-to-date definitions for `RtcPeerConnection` for whatever reason...

### CODE REVIEW

**Comment by erik-moqvist** [comment]
I would like this feature as well.

**Comment by daxpedda** [comment]
@johanhelsing apologies, I made a mistake closing this. #3380 doesn't replace this PR, it only covered a small portion of the API added here.

If you don't mind rebasing this I will review it ASAP.

**Comment by johanhelsing** [comment]
Hey, sorry, I don't have the capacity to continue working on this. Feel free to adopt!

**Comment by daxpedda** [comment]
No problem!

**Pull request closed without merging**
