### PR TITLE
Update WebGPU's webidl

### PR DESCRIPTION
**Pull request by nical**
Regenerated the webidl from the current state of the spec.

### CODE REVIEW

**Comment by nical** [comment]
I would be great to publish a new version soon (for wgpu). What is the policy for new versions with changes to unstable specs?

**Review by Liamolucko — APPROVED** [review]

**Comment by Liamolucko** [comment]
> I would be great to publish a new version soon (for wgpu). What is the policy for new versions with changes to unstable specs?

I don't think there's any policy as such. cc @alexcrichton

**Comment by alexcrichton** [comment]
Nah no policy, just when someone asks

**Comment by nical** [comment]
@alexcrichton in that case, can I haz a new version pretty please 🙏 thanks!

**Comment by alexcrichton** [comment]
If one of y'all would be willing to make a PR for this release that'd be much appreciated which mostly boils down to running `./publish bump` and I can tag/publish the PR when it merge.

**Pull request merged**
