### PR TITLE
add webtransport

### PR DESCRIPTION
**Pull request by darioalessandro**

### CODE REVIEW

**Comment by ten3roberts** [comment]
Looks exciting to see webtransport support in web_sys, which will once make Rust yet more viable on the web and interactive applications.

Is there anything remaining in the PR, or any other thing which is otherwise blocking?

**Comment by daxpedda** [comment]
It's missing updating the `Cargo.toml` `[features]` section, which just needs copying a file after running the generator.
It would also help maintainers if #3303 and #3304 could be closed, whatever this was supposed to mean.

**Comment by darioalessandro** [comment]
Hey @ten3roberts @daxpedda !!! 

Thanks for your interest friends.

I did not realize I was creating a bunch of PRs !! 

I will consolidate all changes here.

**Comment by darioalessandro** [comment]
Hey friends I forced pushed a bad commit and github closed the mr so I had to start fresh https://github.com/rustwasm/wasm-bindgen/pull/3344

**Comment by darioalessandro** [comment]
I created a ticket and tagged some people, I am not sure what's next https://github.com/rustwasm/wasm-bindgen/issues/3345

**Pull request closed without merging**
