### PR TITLE
[WIP] Adds support to enums with values

### PR DESCRIPTION
**Pull request by celsobonutti**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Sorry I don't have a ton of time to help you design this feature. I can try to help review it and see if it's something that makes sense to add, but I can't offer much assistance in the intermediate stages.

**Comment by celsobonutti** [comment]
No problems! I'm afraid I won't have much time to work on this in the near future as I had last week, so this might take a while to progress, but I'll keep working on it. I think I'm slowly understanding everything I need to work on it. :)

**Comment by samvv** [comment]
I'm currently hacking on this feature. I've managed to make the examples compile, but the code generator still needs to be tweaked. Will keep you posted how it goes.

**Comment by samvv** [comment]
Ok so I did a bit more work. I'm looking how to best tackle the modifications in `src/js/mod.rs` of the `cli-support` crate. The current implementation uses a mixture of some temporary data structures and string concatenation, which feels a bit fragile. Maybe we could (ab)use a JavaScript AST such as the one used by [swc](https://swc.rs/)? Or some kind of simple template language? Just thinking out loud here.

**Comment by tnkemdilim** [comment]
@celsobonutti Any possibility I could give this a shot?

**Comment by celsobonutti** [comment]
Hey @tnkemdilim! Sure. Haven't touch this code in a _while_, so I guess it can be a bit outated, though.

**Comment by ZhaoXiangXML** [comment]
I'm working on complete this PR. I've some progress at https://github.com/ZhaoXiangXML/wasm-bindgen/pull/1 however there's still a long way to go.

**Comment by celsobonutti** [comment]
Hey y'all. Unfortunately, I won't be able to keep working on this, as I've changed jobs and no longer have allocated time to do WASM OSS work.

**Pull request closed without merging**
