### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by mtKeller**
This is to resolve: https://github.com/rustwasm/wasm-bindgen/issues/2744
Just need to publish as the current version of wasm-bindgen is from 4 months ago

### CODE REVIEW

**Comment by mtKeller** [comment]
test: build_examples - is not self referential as its installing the old wasm-bindgen from crates
see line 30 and compare with issue

Looking into the windows test now

**Comment by alexcrichton** [comment]
Thanks for the PR! For version bumps though this requires running `./publish bump` after compilling the `publish.rs` script in this repo. Can you also add an entry to `CHANGELOG.md` for the release date?

**Comment by mtKeller** [comment]
My pleasure, thank you all for your hard work.

**Comment by MichealZwen** [comment]
wasm-bindgen maybe version-0.2.78 is incompatible with version-0.2.79, when I use asnycify for await/async.
but i cannot fix it. So I eventually went back to old version, everything becomes fine.

**Comment by mtKeller** [comment]
@MichealZwen Can you provide a test case/error log?

**Comment by MichealZwen** [comment]
@mtKeller Sorry, there's too much detail.
can you provide the update lists from 0.2.78 to 0.2.79?

Basically what I did was compile c/c ++ programs into WebAssembly via Emscripten and package them into static libraries. Finally rust links to the static library and binds javascript interfaces using wasm-bindgen.

As it turns out, the pure Rust version is fine. But c/c ++ programs using Asyncify failed the tescases in 0.2.79.

**Comment by mtKeller** [comment]
I'll see about doing a test. Version bump was a release of all changes from September to current. So there is a bit a room for something to break

https://github.com/rustwasm/wasm-bindgen/compare/0.2.78...0.2.79

**Pull request merged**
