### PR TITLE
Use JsValue for webidl sequence.

### PR DESCRIPTION
**Pull request by derekdreery**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! I'm not sure though if `js_sys::Array` is the right binding here, it looks like according to WebIDL it may suffice to take/return iterators as well? (I'm not super familiar with many of these APIs that take a sequence)

Do you know if other non-array types are accepted/returned?

**Comment by derekdreery** [comment]
I wasn't sure exactly what the semantics are. It sounds like sequences should be valid, but all the examples use `Array`s. Maybe some experimentation is required.

**Comment by alexcrichton** [comment]
Ah yeah it's probably worth playing around with this a bit and some of the newly exposed API. One option is to just bind this as `JsValue` and let users interpret it though

**Comment by derekdreery** [comment]
I've done some experimentation on browsers in https://github.com/rustwasm/wasm-bindgen/issues/1038

**Comment by derekdreery** [comment]
I've just set it to use JsValue for now.

**Comment by alexcrichton** [comment]
Ok looks good to me! Want to add a small test as well exercising this?

Also mind taking a look @fitzgen as well and confirming you're good w/ this strategy?

**Comment by fitzgen** [comment]
Is there a reason not to use `js_sys::Iterator` instead of `JsValue`?

**Comment by alexcrichton** [comment]
@fitzgen I think an `Array` couldn't be passed in because it's not a superclass, right?

**Comment by fitzgen** [comment]
> @fitzgen I think an `Array` couldn't be passed in because it's not a superclass, right?

I'm not suggesting `Array`, only `js_sys::Iterator` which is a duck-typed thing for any JS object that implements the iterator protocol.

Maybe we are talking past each other here?

**Comment by fitzgen** [comment]
Is this issue specifically for parameters?

I would expect `js_sys::Iterator` for iterable return values, and I guess `&JsValue` for parameters.

**Comment by Pauan** [comment]
@alexcrichton Can't you just use `foo(&x.values())`? And we can provide a similar method on other iterable types. Maybe even backed by a trait.

**Comment by alexcrichton** [comment]
@fitzgen ah yeah sorry I'm thinking about parameters, but I think we still need `Array` on return types as well because there's not a `next` method on the `Array` types in JS, right? Ideally we'd return like a `IntoIterator` of some form I think?

@Pauan it's true yeah `.values()` would work! I think we ideally, though, want to expose the capabilities of web engines which is to accept both iterators and arrays so conversions that aren't necessary don't pull in overhead by accident.

**Comment by fitzgen** [comment]
> @fitzgen ah yeah sorry I'm thinking about parameters, but I think we still need `Array` on return types as well because there's not a `next` method on the `Array` types in JS, right? Ideally we'd return like a `IntoIterator` of some form I think?

D'oh. yeah. I don't think we can rely on iterables being arrays though. I guess the most correct thing would be something like `-> impl IntoIterator<Item = JsValue>` or something like that...

**Comment by fitzgen** [comment]
That is pretty definitive. Ignore my comment about "I don't think we can rely on..."

**Comment by alexcrichton** [comment]
Ok I think we're probably good to go in this case with argument position as `JsValue` and return position as `js_sys::Array`. @derekdreery want to update the PR to return `Array` and it should be good to go then!

**Comment by derekdreery** [comment]
Ok sounds good!

**Comment by derekdreery** [comment]
Done. Also rebased and squashed.

**Pull request merged**
