### PR TITLE
Event listeners are also callbacks

### PR DESCRIPTION
**Pull request by fitzgen**
Not sure when it makes sense to land this -- once we support callback interfaces, so we can actually test this?

### CODE REVIEW

**Comment by fitzgen** [comment]
Also, these method name manglings will suck :-/

**Comment by alexcrichton** [comment]
Hm so before we commit to this, how does this work in browsers? How does Gecko accept a function instead of just the callback interface?

**Comment by fitzgen** [comment]
> How does Gecko accept a function instead of just the callback interface?

Asking some firefox DOM folks...

**Comment by fitzgen** [comment]
Hm, actualyl I think we might not want to merge this: https://heycam.github.io/webidl/#es-user-objects

**Pull request closed without merging**
