### PR TITLE
Add bindings for `VisualViewport`

### PR DESCRIPTION
**Pull request by DanielleHuisman**
Add bindings for `VisualViewport`([MDN](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport), [specification](https://drafts.csswg.org/cssom-view/#visualViewport)).

I think the comment about `SameObject` above `window.screen` might also apply to `window.visualViewport`. For now, I just copied the IDL from the specification.

### CODE REVIEW

**Comment by xpe** [comment]
@DanielleHuisman I noticed `VisualViewport` was missing and found this. Thanks!

**Comment by xpe** [comment]
@rustwasm How does this look to you?

**Comment by xpe** [comment]
In the meanwhile, I'll use a fork. But I'm not clear on the syntax. What do I write in `Cargo.toml` to specify a Github fork to provide `web-sys`? -- given that `web-sys` lives in `wasm-bindgen`?

**Comment by xpe** [comment]
I've answered my own question.

## First Attempt (Not Enough)

If one only specifies the git repository of a fork in `Cargo.toml` you will likely see an error like this:

```
% cargo build
    Updating crates.io index
error: failed to select a version for `wasm-bindgen-shared`.
    ... required by package `wasm-bindgen-macro-support v0.2.92 (https://github.com/xpe/wasm-bindgen?branch=feature/visual-viewport#0710b292)`
    ... which satisfies git dependency `wasm-bindgen-macro-support` (locked to 0.2.92) of package `wasm-bindgen-macro v0.2.92 (https://github.com/xpe/wasm-bindgen?branch=feature/visual-viewport#0710b292)`
    ... which satisfies git dependency `wasm-bindgen-macro` (locked to 0.2.92) of package `wasm-bindgen v0.2.92 (https://github.com/xpe/wasm-bindgen?branch=feature/visual-viewport#0710b292)`
    ... which satisfies git dependency `wasm-bindgen` (locked to 0.2.92) of package `web-sys v0.3.69 (https://github.com/xpe/wasm-bindgen?branch=feature/visual-viewport#0710b292)`
    ... which satisfies dependency `web-sys = "^0.3.69"` (locked to 0.3.69) of package `ais-graph v0.1.0 (/Users/xpe/ixe/web/ais-graph)`
versions that meet the requirements `=0.2.92` (locked to 0.2.92) are: 0.2.92

the package `wasm-bindgen-shared` links to the native library `wasm_bindgen`, but it conflicts with a previous package which links to `wasm_bindgen` as well:
package `wasm-bindgen-shared v0.2.92`
    ... which satisfies dependency `wasm-bindgen-shared = "=0.2.92"` of package `wasm-bindgen-macro-support v0.2.92`
    ... which satisfies dependency `wasm-bindgen-macro-support = "=0.2.92"` of package `wasm-bindgen-macro v0.2.92`
    ... which satisfies dependency `wasm-bindgen-macro = "=0.2.92"` of package `wasm-bindgen v0.2.92`
    ... which satisfies dependency `wasm-bindgen = "^0.2.92"` of package `ais-graph v0.1.0 (/Users/xpe/ixe/web/ais-graph)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "wasm_bindgen"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `wasm-bindgen-shared` which could resolve this conflict
``

## Solution

Instead as recommend (see links at bottom), the `[patch]` section of `Cargo.toml` is needed.

With that in mind, here is how I use my fork of `web-sys`:

```toml
[package]
name = "project-name"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = { version = "0.2.92" }
web-sys = { version = "0.3.69", features = [
    "Document",
    "Element",
    "VisualViewport",
    "Window",
] }

[patch.crates-io]
wasm-bindgen = { git = "https://github.com/xpe/wasm-bindgen", branch = "feature/visual-viewport" }
web-sys = { git = "https://github.com/xpe/wasm-bindgen", branch = "feature/visual-viewport" }
```

## Relevant docs and issues

* https://github.com/rust-lang/cargo/issues/1462
* https://github.com/rustwasm/wasm-bindgen/issues/2451
* https://doc.rust-lang.org/1.75.0/cargo/reference/overriding-dependencies.html#the-patch-section

**Comment by xpe** [comment]
@Liamolucko @daxpedda I see that [you both are recent active contributors](https://github.com/rustwasm/wasm-bindgen/graphs/contributors). Could you help @DanielleHuisman and I get this PR merged? Much appreciated.

**Review by Liamolucko — COMMENTED** [review]
Thanks!

Could you add a changelog entry?

**Comment by DanielleHuisman** [comment]
I added a changelog entry. Hope it's all good now :)

**Review by Liamolucko — APPROVED** [review]

**Pull request merged**
