### PR TITLE
Use `convertToBlob` for OffscreenCanvas

### PR DESCRIPTION
**Pull request by namse**
OffscreenCavnas doesn't have method `toBlob` unlike Canvas. Instead of that, OffscreenCanvas has `convertToBlob` method. 
https://html.spec.whatwg.org/multipage/canvas.html#dom-offscreencanvas-converttoblob

### CODE REVIEW

**Comment by daxpedda** [comment]
You need to re-generate the interface.
See https://rustwasm.github.io/docs/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html.

**Comment by daxpedda** [comment]
I don't know how the maintainers see it, but this is a breaking change, I wouldn't consider it as such though, because calling this function before would fail anyway.

But while we are at it @namse, could we also add [`ImageEncodeOptions`](https://html.spec.whatwg.org/multipage/canvas.html#imageencodeoptions) to the WebIDL?

**Comment by namse** [comment]
I didn't `ImageEncodeOptions` because the previous code didn't added `ImageEncodeOptions`.
Give me little time to add it, I think I can add it.

**Comment by namse** [comment]
Wow, it's super easy to put new dictionary type, just paste webidl...!! Good experience to contribute. Thank you for suggestion.
I checked there are no name `ImageEncodeOptions` in other webidl so I think there is no conflict.

**Comment by daxpedda** [comment]
The `web-sys` `[features]` sections has to be updated though, the generator should generate a `features` file somewhere that you can copy.

(we should probably document this in https://rustwasm.github.io/docs/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html)

**Comment by namse** [comment]
Should I `ImageEncodeOptions = ["OffscreenCanvas"]` or `ImageEncodeOptions = []`? I think the second is right because it's not hierarchy relationship between `ImageEncodeOptions` and `OffscreenCanvas`.

**Comment by daxpedda** [comment]
You should probably do whatever the generator spits out, otherwise the next person will overwrite it anyway.
I honestly don't know what the generator does in this case.

**Comment by namse** [comment]
Generator didn't touch Cargo.toml. did I something wrong?

**Comment by daxpedda** [comment]
Unfortunately the generator doesn't do it for you, it just generates a file called `features` (no file extension) in `crates/web-sys`, you should copy it's contents into the `Cargo.toml` `[features]` section of `web-sys`.

This file is gitignored, so you won't see it in your diff.

**Comment by namse** [comment]
Found feature file and overwrite, no git diff. Cool! I was right :) Thank you for explain. Maybe we need a command to put features automatically to Cargo.toml.

**Comment by daxpedda** [comment]
Funny, yeah, this part should probably be added to the wasm-bindgen book.

**Review by daxpedda — APPROVED** [review]
See https://github.com/rustwasm/wasm-bindgen/pull/3341#issuecomment-1458045890 for my thoughts on the breaking change.

Worst case scenario we can keep the old broken API and just deprecate it.

**Comment by daxpedda** [comment]
No, I'm not a maintainer, just a contributor, we have to wait for a maintainer to approve and merge.

On that note, I'm seeing the CI will fail, it got stuck on something unrelated to this PR, probably best to restart it. The only way you can do it as a non-maintainer is just to close and re-open the PR, or force-push.

**Comment by codeart1st** [comment]
I'm also lookig into this get fixed.

**Comment by namse** [comment]
Any maintainer who can review this?

**Comment by alexcrichton** [comment]
Sorry for the delay, but thanks!

**Pull request merged**
