### PR TITLE
Allow changing the `wasm-bindgen-test-runner` timeout via an env variable

### PR DESCRIPTION
**Pull request by expenses**
This PR would close https://github.com/rustwasm/wasm-bindgen/issues/1801.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by tomaka** [comment]
Would it be possible to release a new version with that change in the not-too-far future? :pray: Thanks in advance!

**Comment by alexcrichton** [comment]
Sure thing! I've posted https://github.com/rustwasm/wasm-bindgen/pull/2051 for a release

**Comment by gitmalong** [comment]
it is not documented

**Comment by daxpedda** [comment]
Happy to review a PR documenting this!

**Pull request merged**
