### PR TITLE
 Added out-name flag to the cli, offering an alternative over the crate name

### PR DESCRIPTION
**Pull request by David-OConnor**
Untested! Builds, but unable to test due to this error: 
```
it looks like the Rust project used to create this wasm file was linked against
a different version of wasm-bindgen than this binary:

  rust wasm file: 0.2.29
     this binary: 0.2.12 (d37d4ae81)
```

### CODE REVIEW

**Comment by David-OConnor** [comment]
Looks like there

**Comment by David-OConnor** [comment]
Can't figure out how to make the PR without the old PR files in there

**Comment by chinedufn** [comment]
@David-OConnor WRT to your error have you already tried updating your local `wasm-bindgen-cli` binary?

`cargo install wasm-bindgen-cli -f` would be the easiest way.

Alternatively you could download and unpack a release binary](https://github.com/rustwasm/wasm-bindgen/releases) and move it to your `~/.cargo/bin/` if you don't want to build from source.

**Comment by David-OConnor** [comment]
@chinedufn I think the root cause of that error, and of the bogus files from months ago being committed to the PR, is that I didn't follow the procedures [On this page](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

I'll reattack this when I get home from work

**Pull request closed without merging**
