### PR TITLE
Implement To/FromWasmAbi traits for boxed slices of `JsValue` wrappers

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
Partially addresses #111 and #2452.

~~Typescript type definitions aren't handled yet (still `any[]`)~~

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
Ready for review

**Comment by alexcrichton** [comment]
Seems reasonable enough to me! Can you be sure to add some tests to exercise all these paths too?

**Comment by Jules-Bertholet** [comment]
Tests added!

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
