### PR TITLE
Fix issue 1244

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by alexcrichton** [comment]
whelp

**Comment by fitzgen** [comment]
Looks like a bug in webpack/webassembly-js: https://travis-ci.com/rustwasm/wasm-bindgen/jobs/177248729#L859-L895

```
Failed to decode custom "name" section @619; ignoring (integer representation too long).
Hash: ba0311458107d91706ed
Version: webpack 4.29.3
Time: 28901ms
Built at: 02/12/2019 9:03:06 PM
 2 assets
Entrypoint main = index.js
[0] ./index.js 198 bytes {0} [built]
[1] ./pkg/add.js 199 bytes {1} [built]
[2] ./pkg/add_bg.wasm 1.77 KiB {1} [built] [failed] [1 error]
ERROR in ./pkg/add_bg.wasm
Module parse failed: Unexpected section: 0xfe
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0xfe
    at new CompileError (/home/travis/build/rustwasm/wasm-bindgen/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/home/travis/build/rustwasm/wasm-bindgen/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
    at Object.decode (/home/travis/build/rustwasm/wasm-bindgen/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
    at decode (/home/travis/build/rustwasm/wasm-bindgen/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at WebAssemblyParser.parse (/home/travis/build/rustwasm/wasm-bindgen/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at doBuild.err (/home/travis/build/rustwasm/wasm-bindgen/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/home/travis/build/rustwasm/wasm-bindgen/node_modules/webpack/lib/NormalModule.js:342:12)
    at /home/travis/build/rustwasm/wasm-bindgen/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/travis/build/rustwasm/wasm-bindgen/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/travis/build/rustwasm/wasm-bindgen/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/travis/build/rustwasm/wasm-bindgen/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/travis/build/rustwasm/wasm-bindgen/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/travis/build/rustwasm/wasm-bindgen/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./pkg/add.js 2:0-33 10:11-19
 @ ./index.js
ERROR in chunk 1
89148209054ab87935ec.module.wasm
/home/travis/build/rustwasm/wasm-bindgen/examples/add/pkg/add_bg.wasm
unexpected end
```

**Comment by fitzgen** [comment]
+cc @xtuc ^

Going to merge this.

**Comment by xtuc** [comment]
This looks familiar to me, i'll take a look at it.

**Comment by fitzgen** [comment]
Thanks Sven!

**Comment by lrlna** [comment]
Did this get merged into `0.2.37` then? I am having the same issue as #1246 😅

**Comment by alexcrichton** [comment]
@lrlna this should be published yeah, but you may be running into https://github.com/rustwasm/wasm-bindgen/issues/1267 which is unfortunately still a bug in webpack from what I can tell. It should be fixed by https://github.com/xtuc/webassemblyjs/pull/493 purportedly but I'm trying to figure out how those changes can propagate out to us

**Comment by lrlna** [comment]
Hmmm, possibly! The error I get though is the same as [above](https://github.com/rustwasm/wasm-bindgen/pull/1245#issuecomment-462940737). But! It seems y'all got a fix in for 1267 (yay!), how do I test it out?

**Comment by alexcrichton** [comment]
@lrlna in theory, if it's the same issue, you can just make sure that `webpack` is up to date and has all the latest versions of its dependencies. If you've double checked that though and it's still not working, mind opening a new issue?

**Pull request merged**
