### PR TITLE
Added OffscreenCanvasRenderingContext2D.

### PR DESCRIPTION
**Pull request by scottmunday84**
I wanted to create a way to use OffscreenCanvasRenderingContext2D from Rust. Here's my quick stab at it.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think web-sys may need to be regenerated/reformatted though?

**Comment by scottmunday84** [comment]
Could I get some help on resolving these issues with my PR? The crate builds fine locally, and I attempted running cargo fmt without problem, so I'm going to need some guidance in finishing this. I would love to get my work available.

**Comment by Pauan** [comment]
@scottmunday84 What is your version of rustfmt?

**Comment by scottmunday84** [comment]
rustfmt 1.4.9-nightly (33e36670 2019-10-07)

Sorry about the delay.

**Comment by alexcrichton** [comment]
@scottmunday84 you'll want to update your rustfmt, to the latest stable, and reformat the PR with that. You'll also need to rebase your PR as well.

**Comment by seddonm1** [comment]
@Liamolucko Given you merged https://github.com/rustwasm/wasm-bindgen/pull/3319 I think this PR can be closed?

**Pull request closed without merging**
